# Introduction to Pandas


 - Panel Data Analysis = Pandas

 - High-performance data structures and data analysis tools

- Fast and efficient DataFrame object for data manipulation with integrated indexing

- The DataFrame structure can be seen as a spreadsheet which offers very flexible ways of working with it

- Very easy transforms

- High performance functions for aggregating merging, joining, etc...

In [ ]:
# imports
import pandas as pd
import numpy as np

## The DataFrame object

In [ ]:
# constructing from dictionary

In [ ]:
data = {
    "name": ["Tom Delonge", "Mark Hoppus", "Travis Barker"],
    "class": ["CS180", "CS180", "CS180"],
    "grade": [0.91, 0.85, 0.97]
}

In [ ]:
data

{'class': ['CS180', 'CS180', 'CS180'],
 'grade': [0.91, 0.85, 0.97],
 'name': ['Tom Delonge', 'Mark Hoppus', 'Travis Barker']}

In [ ]:
grades = pd.DataFrame(data)

In [ ]:
grades

            name  class  grade
0    Tom Delonge  CS180   0.91
1    Mark Hoppus  CS180   0.85
2  Travis Barker  CS180   0.97

In [ ]:
# constructing dataframe from an array
arr = np.array(
    [
      ['Tom Delonge', "CS180", 0.91],
      ["Mark Hoppus", "CS180", 0.85],
      ["Travis Barker", "CS180", 0.97]
    ]
)
headers = ["name", "class", "grade"]

grades2 = pd.DataFrame(arr, columns=headers)

In [ ]:
arr

array([['Tom Delonge', 'CS180', '0.91'],
       ['Mark Hoppus', 'CS180', '0.85'],
       ['Travis Barker', 'CS180', '0.97']], dtype='<U13')

In [ ]:
grades2

            name  class grade
0    Tom Delonge  CS180  0.91
1    Mark Hoppus  CS180  0.85
2  Travis Barker  CS180  0.97

## Reading/Writing Data

In [ ]:
import requests
dta = requests.get("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data").text
headers = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'class']

In [ ]:
dta

'5.1,3.5,1.4,0.2,Iris-setosa\n4.9,3.0,1.4,0.2,Iris-setosa\n4.7,3.2,1.3,0.2,Iris-setosa\n4.6,3.1,1.5,0.2,Iris-setosa\n5.0,3.6,1.4,0.2,Iris-setosa\n5.4,3.9,1.7,0.4,Iris-setosa\n4.6,3.4,1.4,0.3,Iris-setosa\n5.0,3.4,1.5,0.2,Iris-setosa\n4.4,2.9,1.4,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n5.4,3.7,1.5,0.2,Iris-setosa\n4.8,3.4,1.6,0.2,Iris-setosa\n4.8,3.0,1.4,0.1,Iris-setosa\n4.3,3.0,1.1,0.1,Iris-setosa\n5.8,4.0,1.2,0.2,Iris-setosa\n5.7,4.4,1.5,0.4,Iris-setosa\n5.4,3.9,1.3,0.4,Iris-setosa\n5.1,3.5,1.4,0.3,Iris-setosa\n5.7,3.8,1.7,0.3,Iris-setosa\n5.1,3.8,1.5,0.3,Iris-setosa\n5.4,3.4,1.7,0.2,Iris-setosa\n5.1,3.7,1.5,0.4,Iris-setosa\n4.6,3.6,1.0,0.2,Iris-setosa\n5.1,3.3,1.7,0.5,Iris-setosa\n4.8,3.4,1.9,0.2,Iris-setosa\n5.0,3.0,1.6,0.2,Iris-setosa\n5.0,3.4,1.6,0.4,Iris-setosa\n5.2,3.5,1.5,0.2,Iris-setosa\n5.2,3.4,1.4,0.2,Iris-setosa\n4.7,3.2,1.6,0.2,Iris-setosa\n4.8,3.1,1.6,0.2,Iris-setosa\n5.4,3.4,1.5,0.4,Iris-setosa\n5.2,4.1,1.5,0.1,Iris-setosa\n5.5,4.2,1.4,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n5.0,3.2,1.2,0.2,Iris-setosa\n5.5,3.5,1.3,0.2,Iris-setosa\n4.9,3.1,1.5,0.1,Iris-setosa\n4.4,3.0,1.3,0.2,Iris-setosa\n5.1,3.4,1.5,0.2,Iris-setosa\n5.0,3.5,1.3,0.3,Iris-setosa\n4.5,2.3,1.3,0.3,Iris-setosa\n4.4,3.2,1.3,0.2,Iris-setosa\n5.0,3.5,1.6,0.6,Iris-setosa\n5.1,3.8,1.9,0.4,Iris-setosa\n4.8,3.0,1.4,0.3,Iris-setosa\n5.1,3.8,1.6,0.2,Iris-setosa\n4.6,3.2,1.4,0.2,Iris-setosa\n5.3,3.7,1.5,0.2,Iris-setosa\n5.0,3.3,1.4,0.2,Iris-setosa\n7.0,3.2,4.7,1.4,Iris-versicolor\n6.4,3.2,4.5,1.5,Iris-versicolor\n6.9,3.1,4.9,1.5,Iris-versicolor\n5.5,2.3,4.0,1.3,Iris-versicolor\n6.5,2.8,4.6,1.5,Iris-versicolor\n5.7,2.8,4.5,1.3,Iris-versicolor\n6.3,3.3,4.7,1.6,Iris-versicolor\n4.9,2.4,3.3,1.0,Iris-versicolor\n6.6,2.9,4.6,1.3,Iris-versicolor\n5.2,2.7,3.9,1.4,Iris-versicolor\n5.0,2.0,3.5,1.0,Iris-versicolor\n5.9,3.0,4.2,1.5,Iris-versicolor\n6.0,2.2,4.0,1.0,Iris-versicolor\n6.1,2.9,4.7,1.4,Iris-versicolor\n5.6,2.9,3.6,1.3,Iris-versicolor\n6.7,3.1,4.4,1.4,Iris-versicolor\n5.6,3.0,4.5,1.5,Iris-versicolor\n5.8,2.7,4.1,1.0,Iris-versicolor\n6.2,2.2,4.5,1.5,Iris-versicolor\n5.6,2.5,3.9,1.1,Iris-versicolor\n5.9,3.2,4.8,1.8,Iris-versicolor\n6.1,2.8,4.0,1.3,Iris-versicolor\n6.3,2.5,4.9,1.5,Iris-versicolor\n6.1,2.8,4.7,1.2,Iris-versicolor\n6.4,2.9,4.3,1.3,Iris-versicolor\n6.6,3.0,4.4,1.4,Iris-versicolor\n6.8,2.8,4.8,1.4,Iris-versicolor\n6.7,3.0,5.0,1.7,Iris-versicolor\n6.0,2.9,4.5,1.5,Iris-versicolor\n5.7,2.6,3.5,1.0,Iris-versicolor\n5.5,2.4,3.8,1.1,Iris-versicolor\n5.5,2.4,3.7,1.0,Iris-versicolor\n5.8,2.7,3.9,1.2,Iris-versicolor\n6.0,2.7,5.1,1.6,Iris-versicolor\n5.4,3.0,4.5,1.5,Iris-versicolor\n6.0,3.4,4.5,1.6,Iris-versicolor\n6.7,3.1,4.7,1.5,Iris-versicolor\n6.3,2.3,4.4,1.3,Iris-versicolor\n5.6,3.0,4.1,1.3,Iris-versicolor\n5.5,2.5,4.0,1.3,Iris-versicolor\n5.5,2.6,4.4,1.2,Iris-versicolor\n6.1,3.0,4.6,1.4,Iris-versicolor\n5.8,2.6,4.0,1.2,Iris-versicolor\n5.0,2.3,3.3,1.0,Iris-versicolor\n5.6,2.7,4.2,1.3,Iris-versicolor\n5.7,3.0,4.2,1.2,Iris-versicolor\n5.7,2.9,4.2,1.3,Iris-versicolor\n6.2,2.9,4.3,1.3,Iris-versicolor\n5.1,2.5,3.0,1.1,Iris-versicolor\n5.7,2.8,4.1,1.3,Iris-versicolor\n6.3,3.3,6.0,2.5,Iris-virginica\n5.8,2.7,5.1,1.9,Iris-virginica\n7.1,3.0,5.9,2.1,Iris-virginica\n6.3,2.9,5.6,1.8,Iris-virginica\n6.5,3.0,5.8,2.2,Iris-virginica\n7.6,3.0,6.6,2.1,Iris-virginica\n4.9,2.5,4.5,1.7,Iris-virginica\n7.3,2.9,6.3,1.8,Iris-virginica\n6.7,2.5,5.8,1.8,Iris-virginica\n7.2,3.6,6.1,2.5,Iris-virginica\n6.5,3.2,5.1,2.0,Iris-virginica\n6.4,2.7,5.3,1.9,Iris-virginica\n6.8,3.0,5.5,2.1,Iris-virginica\n5.7,2.5,5.0,2.0,Iris-virginica\n5.8,2.8,5.1,2.4,Iris-virginica\n6.4,3.2,5.3,2.3,Iris-virginica\n6.5,3.0,5.5,1.8,Iris-virginica\n7.7,3.8,6.7,2.2,Iris-virginica\n7.7,2.6,6.9,2.3,Iris-virginica\n6.0,2.2,5.0,1.5,Iris-virginica\n6.9,3.2,5.7,2.3,Iris-virginica\n5.6,2.8,4.9,2.0,Iris-virginica\n7.7,2.8,6.7,2.0,Iris-virginica\n6.3,2.7,4.9,1.8,Iris-virginica\n6.7,3.3,5.7,2.1,Iris-virginica\n7.2,3.2,6.0,1.8,Iris-virginica\n6.2,2.8,4.8,1.8,Iris-virginica\n6.1,3.0,4.9,1.8,Iris-virginica\n6.4,2.8,5.6,2.1,Iris-virginica\n7.2,3.0,5.8,1.6,Iris-virginica\n7.4,2.8,6.1,1.9,Iris-virginica\n7.9,3.8,6.4,2.0,Iris-virginica\n6.4,2.8,5.6,2.2,Iris-virginica\n6.3,2.8,5.1,1.5,Iris-virginica\n6.1,2.6,5.6,1.4,Iris-virginica\n7.7,3.0,6.1,2.3,Iris-virginica\n6.3,3.4,5.6,2.4,Iris-virginica\n6.4,3.1,5.5,1.8,Iris-virginica\n6.0,3.0,4.8,1.8,Iris-virginica\n6.9,3.1,5.4,2.1,Iris-virginica\n6.7,3.1,5.6,2.4,Iris-virginica\n6.9,3.1,5.1,2.3,Iris-virginica\n5.8,2.7,5.1,1.9,Iris-virginica\n6.8,3.2,5.9,2.3,Iris-virginica\n6.7,3.3,5.7,2.5,Iris-virginica\n6.7,3.0,5.2,2.3,Iris-virginica\n6.3,2.5,5.0,1.9,Iris-virginica\n6.5,3.0,5.2,2.0,Iris-virginica\n6.2,3.4,5.4,2.3,Iris-virginica\n5.9,3.0,5.1,1.8,Iris-virginica\n\n'

In [ ]:
rows = []
for row in dta.splitlines():
    if len(row) == 0:
      continue
    rows.append(row.split(","))

In [ ]:
rows

[['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
 ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
 ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
 ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
 ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
 ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
 ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
 ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
 ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
 ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
 ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
 ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
 ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
 ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
 ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
 ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
 ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
 ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
 ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
 ['5.1', '3.8', '1.5', '0.3', 'Iris-setosa'],
 ['5.4', '3.4', '1.7', '0.2', 'Iris-setosa'],
 ['5.1', '3.7', '1.5', '0.4', 'Iris-setosa'],
 ['4.6', '3.6', '1.0', '0.2', 'Iris-setosa'],
 ['5.1', '3.3', '1.7', '0.5', 'Iris-setosa'],
 ['4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
 ['5.0', '3.0', '1.6', '0.2', 'Iris-setosa'],
 ['5.0', '3.4', '1.6', '0.4', 'Iris-setosa'],
 ['5.2', '3.5', '1.5', '0.2', 'Iris-setosa'],
 ['5.2', '3.4', '1.4', '0.2', 'Iris-setosa'],
 ['4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
 ['4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
 ['5.4', '3.4', '1.5', '0.4', 'Iris-setosa'],
 ['5.2', '4.1', '1.5', '0.1', 'Iris-setosa'],
 ['5.5', '4.2', '1.4', '0.2', 'Iris-setosa'],
 ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
 ['5.0', '3.2', '1.2', '0.2', 'Iris-setosa'],
 ['5.5', '3.5', '1.3', '0.2', 'Iris-setosa'],
 ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
 ['4.4', '3.0', '1.3', '0.2', 'Iris-setosa'],
 ['5.1', '3.4', '1.5', '0.2', 'Iris-setosa'],
 ['5.0', '3.5', '1.3', '0.3', 'Iris-setosa'],
 ['4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
 ['4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
 ['5.0', '3.5', '1.6', '0.6', 'Iris-setosa'],
 ['5.1', '3.8', '1.9', '0.4', 'Iris-setosa'],
 ['4.8', '3.0', '1.4', '0.3', 'Iris-setosa'],
 ['5.1', '3.8', '1.6', '0.2', 'Iris-setosa'],
 ['4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
 ['5.3', '3.7', '1.5', '0.2', 'Iris-setosa'],
 ['5.0', '3.3', '1.4', '0.2', 'Iris-setosa'],
 ['7.0', '3.2', '4.7', '1.4', 'Iris-versicolor'],
 ['6.4', '3.2', '4.5', '1.5', 'Iris-versicolor'],
 ['6.9', '3.1', '4.9', '1.5', 'Iris-versicolor'],
 ['5.5', '2.3', '4.0', '1.3', 'Iris-versicolor'],
 ['6.5', '2.8', '4.6', '1.5', 'Iris-versicolor'],
 ['5.7', '2.8', '4.5', '1.3', 'Iris-versicolor'],
 ['6.3', '3.3', '4.7', '1.6', 'Iris-versicolor'],
 ['4.9', '2.4', '3.3', '1.0', 'Iris-versicolor'],
 ['6.6', '2.9', '4.6', '1.3', 'Iris-versicolor'],
 ['5.2', '2.7', '3.9', '1.4', 'Iris-versicolor'],
 ['5.0', '2.0', '3.5', '1.0', 'Iris-versicolor'],
 ['5.9', '3.0', '4.2', '1.5', 'Iris-versicolor'],
 ['6.0', '2.2', '4.0', '1.0', 'Iris-versicolor'],
 ['6.1', '2.9', '4.7', '1.4', 'Iris-versicolor'],
 ['5.6', '2.9', '3.6', '1.3', 'Iris-versicolor'],
 ['6.7', '3.1', '4.4', '1.4', 'Iris-versicolor'],
 ['5.6', '3.0', '4.5', '1.5', 'Iris-versicolor'],
 ['5.8', '2.7', '4.1', '1.0', 'Iris-versicolor'],
 ['6.2', '2.2', '4.5', '1.5', 'Iris-versicolor'],
 ['5.6', '2.5', '3.9', '1.1', 'Iris-versicolor'],
 ['5.9', '3.2', '4.8', '1.8', 'Iris-versicolor'],
 ['6.1', '2.8', '4.0', '1.3', 'Iris-versicolor'],
 ['6.3', '2.5', '4.9', '1.5', 'Iris-versicolor'],
 ['6.1', '2.8', '4.7', '1.2', 'Iris-versicolor'],
 ['6.4', '2.9', '4.3', '1.3', 'Iris-versicolor'],
 ['6.6', '3.0', '4.4', '1.4', 'Iris-versicolor'],
 ['6.8', '2.8', '4.8', '1.4', 'Iris-versicolor'],
 ['6.7', '3.0', '5.0', '1.7', 'Iris-versicolor'],
 ['6.0', '2.9', '4.5', '1.5', 'Iris-versicolor'],
 ['5.7', '2.6', '3.5', '1.0', 'Iris-versicolor'],
 ['5.5', '2.4', '3.8', '1.1', 'Iris-versicolor'],
 ['5.5', '2.4', '3.7', '1.0', 'Iris-versicolor'],
 ['5.8', '2.7', '3.9', '1.2', 'Iris-versicolor'],
 ['6.0', '2.7', '5.1', '1.6', 'Iris-versicolor'],
 ['5.4', '3.0', '4.5', '1.5', 'Iris-versicolor'],
 ['6.0', '3.4', '4.5', '1.6', 'Iris-versicolor'],
 ['6.7', '3.1', '4.7', '1.5', 'Iris-versicolor'],
 ['6.3', '2.3', '4.4', '1.3', 'Iris-versicolor'],
 ['5.6', '3.0', '4.1', '1.3', 'Iris-versicolor'],
 ['5.5', '2.5', '4.0', '1.3', 'Iris-versicolor'],
 ['5.5', '2.6', '4.4', '1.2', 'Iris-versicolor'],
 ['6.1', '3.0', '4.6', '1.4', 'Iris-versicolor'],
 ['5.8', '2.6', '4.0', '1.2', 'Iris-versicolor'],
 ['5.0', '2.3', '3.3', '1.0', 'Iris-versicolor'],
 ['5.6', '2.7', '4.2', '1.3', 'Iris-versicolor'],
 ['5.7', '3.0', '4.2', '1.2', 'Iris-versicolor'],
 ['5.7', '2.9', '4.2', '1.3', 'Iris-versicolor'],
 ['6.2', '2.9', '4.3', '1.3', 'Iris-versicolor'],
 ['5.1', '2.5', '3.0', '1.1', 'Iris-versicolor'],
 ['5.7', '2.8', '4.1', '1.3', 'Iris-versicolor'],
 ['6.3', '3.3', '6.0', '2.5', 'Iris-virginica'],
 ['5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
 ['7.1', '3.0', '5.9', '2.1', 'Iris-virginica'],
 ['6.3', '2.9', '5.6', '1.8', 'Iris-virginica'],
 ['6.5', '3.0', '5.8', '2.2', 'Iris-virginica'],
 ['7.6', '3.0', '6.6', '2.1', 'Iris-virginica'],
 ['4.9', '2.5', '4.5', '1.7', 'Iris-virginica'],
 ['7.3', '2.9', '6.3', '1.8', 'Iris-virginica'],
 ['6.7', '2.5', '5.8', '1.8', 'Iris-virginica'],
 ['7.2', '3.6', '6.1', '2.5', 'Iris-virginica'],
 ['6.5', '3.2', '5.1', '2.0', 'Iris-virginica'],
 ['6.4', '2.7', '5.3', '1.9', 'Iris-virginica'],
 ['6.8', '3.0', '5.5', '2.1', 'Iris-virginica'],
 ['5.7', '2.5', '5.0', '2.0', 'Iris-virginica'],
 ['5.8', '2.8', '5.1', '2.4', 'Iris-virginica'],
 ['6.4', '3.2', '5.3', '2.3', 'Iris-virginica'],
 ['6.5', '3.0', '5.5', '1.8', 'Iris-virginica'],
 ['7.7', '3.8', '6.7', '2.2', 'Iris-virginica'],
 ['7.7', '2.6', '6.9', '2.3', 'Iris-virginica'],
 ['6.0', '2.2', '5.0', '1.5', 'Iris-virginica'],
 ['6.9', '3.2', '5.7', '2.3', 'Iris-virginica'],
 ['5.6', '2.8', '4.9', '2.0', 'Iris-virginica'],
 ['7.7', '2.8', '6.7', '2.0', 'Iris-virginica'],
 ['6.3', '2.7', '4.9', '1.8', 'Iris-virginica'],
 ['6.7', '3.3', '5.7', '2.1', 'Iris-virginica'],
 ['7.2', '3.2', '6.0', '1.8', 'Iris-virginica'],
 ['6.2', '2.8', '4.8', '1.8', 'Iris-virginica'],
 ['6.1', '3.0', '4.9', '1.8', 'Iris-virginica'],
 ['6.4', '2.8', '5.6', '2.1', 'Iris-virginica'],
 ['7.2', '3.0', '5.8', '1.6', 'Iris-virginica'],
 ['7.4', '2.8', '6.1', '1.9', 'Iris-virginica'],
 ['7.9', '3.8', '6.4', '2.0', 'Iris-virginica'],
 ['6.4', '2.8', '5.6', '2.2', 'Iris-virginica'],
 ['6.3', '2.8', '5.1', '1.5', 'Iris-virginica'],
 ['6.1', '2.6', '5.6', '1.4', 'Iris-virginica'],
 ['7.7', '3.0', '6.1', '2.3', 'Iris-virginica'],
 ['6.3', '3.4', '5.6', '2.4', 'Iris-virginica'],
 ['6.4', '3.1', '5.5', '1.8', 'Iris-virginica'],
 ['6.0', '3.0', '4.8', '1.8', 'Iris-virginica'],
 ['6.9', '3.1', '5.4', '2.1', 'Iris-virginica'],
 ['6.7', '3.1', '5.6', '2.4', 'Iris-virginica'],
 ['6.9', '3.1', '5.1', '2.3', 'Iris-virginica'],
 ['5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
 ['6.8', '3.2', '5.9', '2.3', 'Iris-virginica'],
 ['6.7', '3.3', '5.7', '2.5', 'Iris-virginica'],
 ['6.7', '3.0', '5.2', '2.3', 'Iris-virginica'],
 ['6.3', '2.5', '5.0', '1.9', 'Iris-virginica'],
 ['6.5', '3.0', '5.2', '2.0', 'Iris-virginica'],
 ['6.2', '3.4', '5.4', '2.3', 'Iris-virginica'],
 ['5.9', '3.0', '5.1', '1.8', 'Iris-virginica']]

In [ ]:
iris = pd.DataFrame(rows, columns=headers)
iris["sepal length (cm)"] = iris["sepal length (cm)"].astype(float)
iris["sepal width (cm)"] = iris["sepal width (cm)"].astype(float)
iris["petal length (cm)"] = iris["petal length (cm)"].astype(float)
iris["petal width (cm)"] = iris["petal width (cm)"].astype(float)

In [ ]:
iris.head(10)

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)        class
0                5.1               3.5  ...               0.2  Iris-setosa
1                4.9               3.0  ...               0.2  Iris-setosa
2                4.7               3.2  ...               0.2  Iris-setosa
3                4.6               3.1  ...               0.2  Iris-setosa
4                5.0               3.6  ...               0.2  Iris-setosa
5                5.4               3.9  ...               0.4  Iris-setosa
6                4.6               3.4  ...               0.3  Iris-setosa
7                5.0               3.4  ...               0.2  Iris-setosa
8                4.4               2.9  ...               0.2  Iris-setosa
9                4.9               3.1  ...               0.1  Iris-setosa

[10 rows x 5 columns]

In [ ]:
iris.tail(10)

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)           class
140                6.7               3.1  ...               2.4  Iris-virginica
141                6.9               3.1  ...               2.3  Iris-virginica
142                5.8               2.7  ...               1.9  Iris-virginica
143                6.8               3.2  ...               2.3  Iris-virginica
144                6.7               3.3  ...               2.5  Iris-virginica
145                6.7               3.0  ...               2.3  Iris-virginica
146                6.3               2.5  ...               1.9  Iris-virginica
147                6.5               3.0  ...               2.0  Iris-virginica
148                6.2               3.4  ...               2.3  Iris-virginica
149                5.9               3.0  ...               1.8  Iris-virginica

[10 rows x 5 columns]

In [ ]:
iris

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)           class
0                  5.1               3.5  ...               0.2     Iris-setosa
1                  4.9               3.0  ...               0.2     Iris-setosa
2                  4.7               3.2  ...               0.2     Iris-setosa
3                  4.6               3.1  ...               0.2     Iris-setosa
4                  5.0               3.6  ...               0.2     Iris-setosa
..                 ...               ...  ...               ...             ...
145                6.7               3.0  ...               2.3  Iris-virginica
146                6.3               2.5  ...               1.9  Iris-virginica
147                6.5               3.0  ...               2.0  Iris-virginica
148                6.2               3.4  ...               2.3  Iris-virginica
149                5.9               3.0  ...               1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# write csv
iris.to_csv("iris.csv", index=False)

In [ ]:
# read csv
iris2 = pd.read_csv("iris.csv")

In [ ]:
iris2

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)           class
0                  5.1               3.5  ...               0.2     Iris-setosa
1                  4.9               3.0  ...               0.2     Iris-setosa
2                  4.7               3.2  ...               0.2     Iris-setosa
3                  4.6               3.1  ...               0.2     Iris-setosa
4                  5.0               3.6  ...               0.2     Iris-setosa
..                 ...               ...  ...               ...             ...
145                6.7               3.0  ...               2.3  Iris-virginica
146                6.3               2.5  ...               1.9  Iris-virginica
147                6.5               3.0  ...               2.0  Iris-virginica
148                6.2               3.4  ...               2.3  Iris-virginica
149                5.9               3.0  ...               1.8  Iris-virginica

[150 rows x 5 columns]

## Descriptive functions

In [ ]:
# value counts
iris.value_counts("class")

class
Iris-virginica     50
Iris-versicolor    50
Iris-setosa        50
dtype: int64

In [ ]:
# describe
summary = iris.describe()

In [ ]:
summary

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.054000           3.758667          1.198667
std             0.828066          0.433594           1.764420          0.763161
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [ ]:
summary.loc["count"]["sepal length (cm)"]

150.0

In [ ]:
iris.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
class                 object
dtype: object

## Selecting Data

In [ ]:
# selecting columns
iris["sepal length (cm)"] # a single name

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [ ]:
iris[["sepal length (cm)", "sepal width (cm)", "class"]] # list of name

     sepal length (cm)  sepal width (cm)           class
0                  5.1               3.5     Iris-setosa
1                  4.9               3.0     Iris-setosa
2                  4.7               3.2     Iris-setosa
3                  4.6               3.1     Iris-setosa
4                  5.0               3.6     Iris-setosa
..                 ...               ...             ...
145                6.7               3.0  Iris-virginica
146                6.3               2.5  Iris-virginica
147                6.5               3.0  Iris-virginica
148                6.2               3.4  Iris-virginica
149                5.9               3.0  Iris-virginica

[150 rows x 3 columns]

In [ ]:
# selecting rows
iris.loc[0:10] # can be strings or integers. Named location

    sepal length (cm)  sepal width (cm)  ...  petal width (cm)        class
0                 5.1               3.5  ...               0.2  Iris-setosa
1                 4.9               3.0  ...               0.2  Iris-setosa
2                 4.7               3.2  ...               0.2  Iris-setosa
3                 4.6               3.1  ...               0.2  Iris-setosa
4                 5.0               3.6  ...               0.2  Iris-setosa
5                 5.4               3.9  ...               0.4  Iris-setosa
6                 4.6               3.4  ...               0.3  Iris-setosa
7                 5.0               3.4  ...               0.2  Iris-setosa
8                 4.4               2.9  ...               0.2  Iris-setosa
9                 4.9               3.1  ...               0.1  Iris-setosa
10                5.4               3.7  ...               0.2  Iris-setosa

[11 rows x 5 columns]

In [ ]:
iris.iloc[0:5] # always expect integer

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)        class
0                5.1               3.5  ...               0.2  Iris-setosa
1                4.9               3.0  ...               0.2  Iris-setosa
2                4.7               3.2  ...               0.2  Iris-setosa
3                4.6               3.1  ...               0.2  Iris-setosa
4                5.0               3.6  ...               0.2  Iris-setosa

[5 rows x 5 columns]

## Transforming Data

In [ ]:
# adding columns
iris['cost'] = 0.0

In [ ]:
iris.head()

   sepal length (cm)  sepal width (cm)  ...        class  cost
0                5.1               3.5  ...  Iris-setosa   0.0
1                4.9               3.0  ...  Iris-setosa   0.0
2                4.7               3.2  ...  Iris-setosa   0.0
3                4.6               3.1  ...  Iris-setosa   0.0
4                5.0               3.6  ...  Iris-setosa   0.0

[5 rows x 6 columns]

In [ ]:
iris["country"] = "usa"

In [ ]:
iris.head()

   sepal length (cm)  sepal width (cm)  ...  cost  country
0                5.1               3.5  ...   0.0      usa
1                4.9               3.0  ...   0.0      usa
2                4.7               3.2  ...   0.0      usa
3                4.6               3.1  ...   0.0      usa
4                5.0               3.6  ...   0.0      usa

[5 rows x 7 columns]

In [ ]:
# vectorized columns operations
iris["sum"] = iris["sepal length (cm)"] + iris["petal length (cm)"]

In [ ]:
iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  ...  cost country  sum
0                5.1               3.5                1.4  ...   0.0     usa  6.5
1                4.9               3.0                1.4  ...   0.0     usa  6.3
2                4.7               3.2                1.3  ...   0.0     usa  6.0
3                4.6               3.1                1.5  ...   0.0     usa  6.1
4                5.0               3.6                1.4  ...   0.0     usa  6.4

[5 rows x 8 columns]

## Filtering

In [ ]:
iris.shape

(150, 8)

In [ ]:
iris["sepal length (cm)"] < 5.0

0      False
1       True
2       True
3       True
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: sepal length (cm), Length: 150, dtype: bool

In [ ]:
iris["class"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
filtered = iris[iris["class"] == "Iris-virginica"]

In [ ]:
filtered["class"].unique()

array(['Iris-virginica'], dtype=object)

In [ ]:
iris[iris["sepal length (cm)"] < 5]

     sepal length (cm)  sepal width (cm)  petal length (cm)  ...  cost country  sum
1                  4.9               3.0                1.4  ...   0.0     usa  6.3
2                  4.7               3.2                1.3  ...   0.0     usa  6.0
3                  4.6               3.1                1.5  ...   0.0     usa  6.1
6                  4.6               3.4                1.4  ...   0.0     usa  6.0
8                  4.4               2.9                1.4  ...   0.0     usa  5.8
9                  4.9               3.1                1.5  ...   0.0     usa  6.4
11                 4.8               3.4                1.6  ...   0.0     usa  6.4
12                 4.8               3.0                1.4  ...   0.0     usa  6.2
13                 4.3               3.0                1.1  ...   0.0     usa  5.4
22                 4.6               3.6                1.0  ...   0.0     usa  5.6
24                 4.8               3.4                1.9  ...   0.0     usa  6.7
29                 4.7               3.2                1.6  ...   0.0     usa  6.3
30                 4.8               3.1                1.6  ...   0.0     usa  6.4
34                 4.9               3.1                1.5  ...   0.0     usa  6.4
37                 4.9               3.1                1.5  ...   0.0     usa  6.4
38                 4.4               3.0                1.3  ...   0.0     usa  5.7
41                 4.5               2.3                1.3  ...   0.0     usa  5.8
42                 4.4               3.2                1.3  ...   0.0     usa  5.7
45                 4.8               3.0                1.4  ...   0.0     usa  6.2
47                 4.6               3.2                1.4  ...   0.0     usa  6.0
57                 4.9               2.4                3.3  ...   0.0     usa  8.2
106                4.9               2.5                4.5  ...   0.0     usa  9.4

[22 rows x 8 columns]

## Grouping and aggregating

### split-apply-combine
![image.png]()

In [ ]:
# iris example
groups = iris.groupby("class")

In [ ]:
for id, block in groups:
  print(id)
  print(block.head())

Iris-setosa
   sepal length (cm)  sepal width (cm)  petal length (cm)  ...  cost country  sum
0                5.1               3.5                1.4  ...   0.0     usa  6.5
1                4.9               3.0                1.4  ...   0.0     usa  6.3
2                4.7               3.2                1.3  ...   0.0     usa  6.0
3                4.6               3.1                1.5  ...   0.0     usa  6.1
4                5.0               3.6                1.4  ...   0.0     usa  6.4

[5 rows x 8 columns]
Iris-versicolor
    sepal length (cm)  sepal width (cm)  petal length (cm)  ...  cost country   sum
50                7.0               3.2                4.7  ...   0.0     usa  11.7
51                6.4               3.2                4.5  ...   0.0     usa  10.9
52                6.9               3.1                4.9  ...   0.0     usa  11.8
53                5.5               2.3                4.0  ...   0.0     usa   9.5
54                6.5               2.8                4.6  ...   0.0     usa  11.1

[5 rows x 8 columns]
Iris-virginica
     sepal length (cm)  sepal width (cm)  petal length (cm)  ...  cost country   sum
100                6.3               3.3                6.0  ...   0.0     usa  12.3
101                5.8               2.7                5.1  ...   0.0     usa  10.9
102                7.1               3.0                5.9  ...   0.0     usa  13.0
103                6.3               2.9                5.6  ...   0.0     usa  11.9
104                6.5               3.0                5.8  ...   0.0     usa  12.3

[5 rows x 8 columns]

In [ ]:
groups.mean()

                 sepal length (cm)  sepal width (cm)  ...  cost     sum
class                                                 ...
Iris-setosa                  5.006             3.418  ...   0.0   6.470
Iris-versicolor              5.936             2.770  ...   0.0  10.196
Iris-virginica               6.588             2.974  ...   0.0  12.140

[3 rows x 6 columns]

In [ ]:
# CA housing example

In [ ]:
headers = [
  "age",
  "workclass",
  "fnlwgt",
  "education",
  "education-num",
  "marital-status",
  "occupation",
  "relationship",
  "race",
  "sex",
  "capital-gain",
  "capital-loss",
  "hours-per-week",
  "native-country",
  "income"
]

In [ ]:
adult = pd.read_csv("adult.data", header=None)
adult.columns=headers

In [ ]:
adult

       age          workclass  fnlwgt  ... hours-per-week  native-country  income
0       39          State-gov   77516  ...             40   United-States   <=50K
1       50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2       38            Private  215646  ...             40   United-States   <=50K
3       53            Private  234721  ...             40   United-States   <=50K
4       28            Private  338409  ...             40            Cuba   <=50K
...    ...                ...     ...  ...            ...             ...     ...
32556   27            Private  257302  ...             38   United-States   <=50K
32557   40            Private  154374  ...             40   United-States    >50K
32558   58            Private  151910  ...             40   United-States   <=50K
32559   22            Private  201490  ...             20   United-States   <=50K
32560   52       Self-emp-inc  287927  ...             40   United-States    >50K

[32561 rows x 15 columns]

In [ ]:
# adult example

In [ ]:
adult[["age","hours-per-week"]].groupby("age").mean()

     hours-per-week
age
17        21.367089
18        25.912727
19        30.678371
20        32.280212
21        34.034722
..              ...
85        29.333333
86        40.000000
87         2.000000
88        40.000000
90        36.813953

[73 rows x 1 columns]

In [ ]:
adult[["age","hours-per-week"]].groupby("age").mean().sort_values("hours-per-week")

     hours-per-week
age
87         2.000000
82        17.416667
17        21.367089
81        21.700000
74        22.607843
..              ...
49        43.753899
35        43.908676
50        43.953488
38        44.053204
44        44.129834

[73 rows x 1 columns]

In [ ]:
adult[["age", "sex","hours-per-week"]].groupby(["age","sex"]).mean()

             hours-per-week
age sex
17   Female       19.940860
     Male         22.636364
18   Female       25.070896
     Male         26.712766
19   Female       28.662921
...                     ...
87   Male          2.000000
88   Female       40.000000
     Male         40.000000
90   Female       31.500000
     Male         39.379310

[144 rows x 1 columns]

### Cross-tabs

In [ ]:
pd.crosstab(
    index=adult["sex"],
    columns=adult['race']
)

race      Amer-Indian-Eskimo   Asian-Pac-Islander   Black   Other   White
sex
 Female                  119                  346    1555     109    8642
 Male                    192                  693    1569     162   19174

### Pivot tables

In [ ]:
pd.pivot_table(
    data= adult, 
    values='hours-per-week', 
    index=["sex"],
    columns=['race', 'education'], 
    aggfunc=np.mean
)

race       Amer-Indian-Eskimo             ...        White
education                10th       11th  ...  Prof-school  Some-college
sex                                       ...
 Female                  32.5  20.000000  ...    45.341772     34.243279
 Male                    44.9  40.363636  ...    47.891954     41.709751

[2 rows x 79 columns]

## Joining

![image.png]()

In [ ]:
iris["class"].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: class, dtype: int64

In [ ]:
new_data = {
    "class": ["Iris-virginica", "Iris-setosa", "Iris-metallica"],
    "cost": [12.50, 9.25, 110.0]
}
cost_data = pd.DataFrame(new_data)

In [ ]:
cost_data

            class    cost
0  Iris-virginica   12.50
1     Iris-setosa    9.25
2  Iris-metallica  110.00

In [ ]:
costs = pd.merge(left=iris, right=cost_data, on="class", how="inner")

In [ ]:
costs.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  ...  country  sum  cost_y
0                5.1               3.5                1.4  ...      usa  6.5    9.25
1                4.9               3.0                1.4  ...      usa  6.3    9.25
2                4.7               3.2                1.3  ...      usa  6.0    9.25
3                4.6               3.1                1.5  ...      usa  6.1    9.25
4                5.0               3.6                1.4  ...      usa  6.4    9.25

[5 rows x 9 columns]

In [ ]:
costs[costs["class"]=="Iris-versicolor"]

Empty DataFrame
Columns: [sepal length (cm), sepal width (cm), petal length (cm), petal width (cm), class, cost_x, country, sum, cost_y]
Index: []

In [ ]:
costs["class"].value_counts()

Iris-setosa       50
Iris-virginica    50
Name: class, dtype: int64